/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;
import Controller.UsuarioController;
import Model.Usuario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author devmat
 */
public class Tela_login extends javax.swing.JFrame {

    /**
     * Creates new form Tela_login
     */
    public Tela_login() {
        initComponents();
    }
    
    
    
    
    public void mostrarCadastroUsuario() {
    try {
        // Captura os dados via JOptionPane
        String nome = JOptionPane.showInputDialog(this, "Digite seu nome:", "Cadastro de Usuário", JOptionPane.PLAIN_MESSAGE);
        if (nome == null || nome.trim().isEmpty()) return;

        String email = JOptionPane.showInputDialog(this, "Digite seu e-mail:", "Cadastro de Usuário", JOptionPane.PLAIN_MESSAGE);
        if (email == null || email.trim().isEmpty()) return;

        String senha = JOptionPane.showInputDialog(this, "Digite sua senha:", "Cadastro de Usuário", JOptionPane.PLAIN_MESSAGE);
        if (senha == null || senha.trim().isEmpty()) return;

        String cpf = JOptionPane.showInputDialog(this, "Digite seu CPF:", "Cadastro de Usuário", JOptionPane.PLAIN_MESSAGE);
        if (cpf == null || cpf.trim().isEmpty()) return;

        String dataStr = JOptionPane.showInputDialog(this, "Digite sua Data de Nascimento (dd/MM/yyyy):", "Cadastro de Usuário", JOptionPane.PLAIN_MESSAGE);
        if (dataStr == null || dataStr.trim().isEmpty()) return;

        // Convertendo String para Date
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        Date dataNascimento = formatador.parse(dataStr);
        
        // Criando objeto do usuário
        Usuario novoUsuario = new Usuario();
        novoUsuario.setNome(nome);
        novoUsuario.setEmail(email);
        novoUsuario.setSenha(senha);
        novoUsuario.setCpf(cpf);
        novoUsuario.setDataNascimento(new java.sql.Date(dataNascimento.getTime()));

        // Chamando o método de cadastro no controller
        UsuarioController usuarioController = new UsuarioController();
        boolean sucesso = usuarioController.cadastrandoUsuario(novoUsuario);

        // Exibindo resultado
        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar usuário!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this, "Formato de data inválido! Use dd/MM/yyyy.", "Erro", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro inesperado: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_login = new javax.swing.JPanel();
        login = new javax.swing.JToggleButton();
        campo_usuario = new javax.swing.JTextField();
        campo_senha = new javax.swing.JTextField();
        texto_usuario = new javax.swing.JLabel();
        texto_senha = new javax.swing.JLabel();
        recuperrar_senha = new javax.swing.JButton();
        criar_conta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel_login.setBackground(new java.awt.Color(0, 255, 204));
        painel_login.setMaximumSize(new java.awt.Dimension(1920, 1080));
        painel_login.setMinimumSize(new java.awt.Dimension(1920, 1080));
        painel_login.setPreferredSize(new java.awt.Dimension(1920, 1080));
        painel_login.setRequestFocusEnabled(false);

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        campo_usuario.setText("Usuário");
        campo_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_usuarioActionPerformed(evt);
            }
        });

        campo_senha.setText("Senha");

        texto_usuario.setText("Usuário:");

        texto_senha.setText("Senha:");

        recuperrar_senha.setBackground(new java.awt.Color(204, 204, 204));
        recuperrar_senha.setText("Recuperar senha");

        criar_conta.setBackground(new java.awt.Color(204, 204, 204));
        criar_conta.setText("Criar uma conta");
        criar_conta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criar_contaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_loginLayout = new javax.swing.GroupLayout(painel_login);
        painel_login.setLayout(painel_loginLayout);
        painel_loginLayout.setHorizontalGroup(
            painel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_loginLayout.createSequentialGroup()
                .addGroup(painel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_loginLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addGroup(painel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painel_loginLayout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addGroup(painel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(criar_conta, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recuperrar_senha)
                            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(1361, Short.MAX_VALUE))
        );
        painel_loginLayout.setVerticalGroup(
            painel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_loginLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(texto_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(texto_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campo_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recuperrar_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(criar_conta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(710, Short.MAX_VALUE))
        );

        getContentPane().add(painel_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 533));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        // criar um objeto da classe LoginController
        LoginController controller = new LoginController();
        // criando variavel que receba o retorno do metodo autenticar
        Usuario logou = controller.authenticate(
          campousuario.getText(),campo_senha.getText());
        
        if(logou !=null){
          JOptionPane.showMessageDialog(null,"Usuario logado com sucesso! "+ logou.getNome());
          // abrir a tela Home
          Tela_home home = new Tela_home(logou);
          home.setVisible(true);
          // fechando tela de login
          dispose();
          
        }else{
            JOptionPane.showMessageDialog(null,"Usuario não encontrado!");
        }
    }//GEN-LAST:event_loginActionPerformed

    private void campo_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_usuarioActionPerformed

    private void criar_contaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criar_contaActionPerformed
        // TODO add your handling code here:
        mostrarCadastroUsuario();
    }//GEN-LAST:event_criar_contaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo_senha;
    private javax.swing.JTextField campo_usuario;
    private javax.swing.JButton criar_conta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton login;
    private javax.swing.JPanel painel_login;
    private javax.swing.JButton recuperrar_senha;
    private javax.swing.JLabel texto_senha;
    private javax.swing.JLabel texto_usuario;
    // End of variables declaration//GEN-END:variables
}
