/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author devmat
 */
public class Tela_ordens_de_servico extends javax.swing.JFrame {

    /**
     * Creates new form Tela_ordens_de_servico
     */
    public Tela_ordens_de_servico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_ordens_de_servico = new javax.swing.JPanel();
        texto_ordens_de_servico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(1920, 1080, 1080, 1080));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel_ordens_de_servico.setMaximumSize(new java.awt.Dimension(1920, 1080));
        painel_ordens_de_servico.setMinimumSize(new java.awt.Dimension(1920, 1080));
        painel_ordens_de_servico.setVerifyInputWhenFocusTarget(false);

        texto_ordens_de_servico.setMaximumSize(new java.awt.Dimension(1920, 1080));
        texto_ordens_de_servico.setMinimumSize(new java.awt.Dimension(1920, 1080));
        texto_ordens_de_servico.setPreferredSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout painel_ordens_de_servicoLayout = new javax.swing.GroupLayout(painel_ordens_de_servico);
        painel_ordens_de_servico.setLayout(painel_ordens_de_servicoLayout);
        painel_ordens_de_servicoLayout.setHorizontalGroup(
            painel_ordens_de_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_ordens_de_servicoLayout.createSequentialGroup()
                .addComponent(texto_ordens_de_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 948, Short.MAX_VALUE))
        );
        painel_ordens_de_servicoLayout.setVerticalGroup(
            painel_ordens_de_servicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_ordens_de_servicoLayout.createSequentialGroup()
                .addComponent(texto_ordens_de_servico, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 507, Short.MAX_VALUE))
        );

        getContentPane().add(painel_ordens_de_servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_ordens_de_servico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_ordens_de_servico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_ordens_de_servico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_ordens_de_servico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_ordens_de_servico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel painel_ordens_de_servico;
    private javax.swing.JLabel texto_ordens_de_servico;
    // End of variables declaration//GEN-END:variables
}
